dist: trusty
sudo: required
services:
  - docker
language: go
go:
- "1.14"

env:
  - GOMAXPROCS=4 GO111MODULE=on GOPROXY=https://proxy.golang.org/

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- make tools

before_script:
- git config --global url.https://github.com/.insteadOf ssh://git@github.com/

script:
- make fmtcheck generate
- bash scripts/travis.sh
- go mod verify
- GOOS=windows go build -mod=vendor

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip